table 'Internet Sales'

	measure 'Internet Distinct Count Sales Order' = DISTINCTCOUNT([Sales Order Number])

	measure 'Internet Order Lines Count' = COUNTA([Sales Order Line Number])

	measure 'Internet Total Units' = SUM([Order Quantity])

	measure 'Internet Total Discount Amount' = SUM([Discount Amount])

	measure 'Internet Total Product Cost' = SUM([Total Product Cost])
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	measure 'Internet Total Sales' = SUM([Sales Amount])
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	measure 'Internet Total Margin' = SUM([Margin])
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	measure 'Internet Total Freight' = SUM([Freight])
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	measure 'Internet Previous Quarter Margin' = CALCULATE([Internet Total Margin],PREVIOUSQUARTER('Date'[Date]))

	measure 'Internet Current Quarter Margin' = TOTALQTD([Internet Total Margin],'Date'[Date])

	measure 'Internet Previous Quarter Margin Proportion to QTD' = [Internet Previous Quarter Margin]*([Days Current Quarter to Date]/[Days In Current Quarter])

	measure 'Internet Previous Quarter Sales' = CALCULATE([Internet Total Sales],PREVIOUSQUARTER('Date'[Date]))

	measure 'Internet Current Quarter Sales' = TOTALQTD([Internet Total Sales],'Date'[Date])

	measure 'Internet Current AVG Sales' = AVG([Internet Total Sales],'Date'[Date])

	measure 'Internet Previous Quarter Sales Proportion to QTD' = [Internet Previous Quarter Sales]*([Days Current Quarter to Date]/[Days In Current Quarter])

	measure 'Internet Current Quarter Sales Performance' = IFERROR([Internet Current Quarter Sales]/[Internet Previous Quarter Sales Proportion to QTD],BLANK())

		KPI
			targetExpression = 1.1
			statusGraphic: Shapes
			statusExpression =
				var x='Internet Sales'[Internet Current Quarter Sales Performance] return
				            if(ISBLANK(x),BLANK(),
				                    If(x<1,-1,
					                If(x<1.07,0,1)
				                )
				            )
				            

			annotation GoalType = StaticValue

			annotation KpiStatusType = Linear

			annotation KpiThresholdType = Absolute

			annotation KpiThresholdOrdering = Ascending

			annotation KpiThresholdCount = 2

			annotation KpiThreshold_0 = 1

			annotation KpiThreshold_1 = 1.07

	measure 'Internet Current Quarter Margin Performance' = IF([Internet Previous Quarter Margin Proportion to QTD]<>0,([Internet Current Quarter Margin]-[Internet Previous Quarter Margin Proportion to QTD])/[Internet Previous Quarter Margin Proportion to QTD],BLANK())

		KPI
			targetExpression = 1.25
			statusGraphic: Shapes
			statusExpression =
				var x='Internet Sales'[Internet Current Quarter Margin Performance] return
				            if(ISBLANK(x),BLANK(),
				                    If(x<0.8,-1,
					                If(x<1.03,0,1)
				                )
				            )
				            

			annotation GoalType = StaticValue

			annotation KpiStatusType = Linear

			annotation KpiThresholdType = Absolute

			annotation KpiThresholdOrdering = Ascending

			annotation KpiThresholdCount = 2

			annotation KpiThreshold_0 = 0.8

			annotation KpiThreshold_1 = 1.03

	column 'Product Id'
		dataType: Int64
		sourceProviderType: Integer
		sourceColumn: ProductKey

	column 'Customer Id'
		dataType: Int64
		sourceProviderType: Integer
		sourceColumn: CustomerKey

	column 'Promotion Id'
		dataType: Int64
		sourceProviderType: Integer
		sourceColumn: PromotionKey

	column 'Currency Id'
		dataType: Int64
		sourceProviderType: Integer
		sourceColumn: CurrencyKey

	column 'Sales Territory Id'
		dataType: Int64
		sourceProviderType: Integer
		sourceColumn: SalesTerritoryKey

	column 'Sales Order Number'
		dataType: String
		sourceProviderType: WChar
		sourceColumn: SalesOrderNumber

	column 'Sales Order Line Number'
		dataType: Int64
		sourceProviderType: UnsignedTinyInt
		sourceColumn: SalesOrderLineNumber

	column 'Revision Number'
		dataType: Int64
		sourceProviderType: UnsignedTinyInt
		sourceColumn: RevisionNumber

	column 'Order Quantity'
		dataType: Int64
		sourceProviderType: SmallInt
		sourceColumn: OrderQuantity

	column 'Unit Price'
		dataType: Decimal
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00
		sourceProviderType: Currency
		sourceColumn: UnitPrice

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Extended Amount'
		dataType: Decimal
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00
		sourceProviderType: Currency
		sourceColumn: ExtendedAmount

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Unit Price Discount Pct'
		dataType: Double
		sourceProviderType: Double
		sourceColumn: UnitPriceDiscountPct

	column 'Discount Amount'
		dataType: Double
		sourceProviderType: Double
		sourceColumn: DiscountAmount

	column 'Product Standard Cost'
		dataType: Decimal
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00
		sourceProviderType: Currency
		sourceColumn: ProductStandardCost

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Total Product Cost'
		dataType: Decimal
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00
		sourceProviderType: Currency
		sourceColumn: TotalProductCost

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Sales Amount'
		dataType: Decimal
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00
		sourceProviderType: Currency
		sourceColumn: SalesAmount

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Tax Amt'
		dataType: Decimal
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00
		sourceProviderType: Currency
		sourceColumn: TaxAmt

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column Freight
		dataType: Decimal
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00
		sourceProviderType: Currency
		sourceColumn: Freight

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	column 'Carrier Tracking Number'
		dataType: String
		sourceProviderType: WChar
		sourceColumn: CarrierTrackingNumber

	column 'Customer PO Number'
		dataType: String
		sourceProviderType: WChar
		sourceColumn: CustomerPONumber

	column 'Order Date'
		dataType: DateTime
		formatString = General Date
		sourceProviderType: DBTimeStamp
		sourceColumn: OrderDate

	column 'Due Date'
		dataType: DateTime
		formatString = General Date
		sourceProviderType: DBTimeStamp
		sourceColumn: DueDate

	column 'Ship Date'
		dataType: DateTime
		formatString = General Date
		sourceProviderType: DBTimeStamp
		sourceColumn: ShipDate

	column Margin = [Sales Amount]-[Total Product Cost]
		dataType: Decimal
		formatString = \$#,0.00;(\$#,0.00);\$#,0.00
		isDataTypeInferred

		annotation Format = <Format Format="Currency" Accuracy="2" ThousandSeparator="True"><Currency LCID="1033" DisplayName="$ English (United States)" Symbol="$" PositivePattern="0" NegativePattern="0" /></Format>

	partition 'Internet Sales' = Query
		query =
			SELECT   
			[dbo].[FactInternetSales].[ProductKey],  
			[dbo].[FactInternetSales].[CustomerKey],  
			[dbo].[FactInternetSales].[PromotionKey],  
			[dbo].[FactInternetSales].[CurrencyKey],  
			[dbo].[FactInternetSales].[SalesTerritoryKey],  
			[dbo].[FactInternetSales].[SalesOrderNumber],  
			[dbo].[FactInternetSales].[SalesOrderLineNumber],  
			[dbo].[FactInternetSales].[RevisionNumber],  
			[dbo].[FactInternetSales].[OrderQuantity],  
			[dbo].[FactInternetSales].[UnitPrice],  
			[dbo].[FactInternetSales].[ExtendedAmount],  
			[dbo].[FactInternetSales].[UnitPriceDiscountPct],  
			[dbo].[FactInternetSales].[DiscountAmount],  
			[dbo].[FactInternetSales].[ProductStandardCost],  
			[dbo].[FactInternetSales].[TotalProductCost],  
			[dbo].[FactInternetSales].[SalesAmount],  
			[dbo].[FactInternetSales].[TaxAmt],  
			[dbo].[FactInternetSales].[Freight],  
			[dbo].[FactInternetSales].[CarrierTrackingNumber],  
			[dbo].[FactInternetSales].[CustomerPONumber],  
			[dbo].[FactInternetSales].[OrderDate],  
			[dbo].[FactInternetSales].[DueDate],  
			[dbo].[FactInternetSales].[ShipDate]   
			FROM [dbo].[FactInternetSales]
		dataSource: 'Adventure Works DB from SQL'

		annotation QueryEditorSerialization =
				<?xml version="1.0" encoding="UTF-16"?><Gemini xmlns="QueryEditorSerialization"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT   
				[dbo].[FactInternetSales].[ProductKey],  
				[dbo].[FactInternetSales].[CustomerKey],  
				[dbo].[FactInternetSales].[PromotionKey],  
				[dbo].[FactInternetSales].[CurrencyKey],  
				[dbo].[FactInternetSales].[SalesTerritoryKey],  
				[dbo].[FactInternetSales].[SalesOrderNumber],  
				[dbo].[FactInternetSales].[SalesOrderLineNumber],  
				[dbo].[FactInternetSales].[RevisionNumber],  
				[dbo].[FactInternetSales].[OrderQuantity],  
				[dbo].[FactInternetSales].[UnitPrice],  
				[dbo].[FactInternetSales].[ExtendedAmount],  
				[dbo].[FactInternetSales].[UnitPriceDiscountPct],  
				[dbo].[FactInternetSales].[DiscountAmount],  
				[dbo].[FactInternetSales].[ProductStandardCost],  
				[dbo].[FactInternetSales].[TotalProductCost],  
				[dbo].[FactInternetSales].[SalesAmount],  
				[dbo].[FactInternetSales].[TaxAmt],  
				[dbo].[FactInternetSales].[Freight],  
				[dbo].[FactInternetSales].[CarrierTrackingNumber],  
				[dbo].[FactInternetSales].[CustomerPONumber],  
				[dbo].[FactInternetSales].[OrderDate],  
				[dbo].[FactInternetSales].[DueDate],  
				[dbo].[FactInternetSales].[ShipDate]   
				FROM [dbo].[FactInternetSales]</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>

	annotation _TM_ExtProp_QueryDefinition =  SELECT [dbo].[FactInternetSales].[ProductKey],[dbo].[FactInternetSales].[CustomerKey],[dbo].[FactInternetSales].[PromotionKey],[dbo].[FactInternetSales].[CurrencyKey],[dbo].[FactInternetSales].[SalesTerritoryKey],[dbo].[FactInternetSales].[SalesOrderNumber],[dbo].[FactInternetSales].[SalesOrderLineNumber],[dbo].[FactInternetSales].[RevisionNumber],[dbo].[FactInternetSales].[OrderQuantity],[dbo].[FactInternetSales].[UnitPrice],[dbo].[FactInternetSales].[ExtendedAmount],[dbo].[FactInternetSales].[UnitPriceDiscountPct],[dbo].[FactInternetSales].[DiscountAmount],[dbo].[FactInternetSales].[ProductStandardCost],[dbo].[FactInternetSales].[TotalProductCost],[dbo].[FactInternetSales].[SalesAmount],[dbo].[FactInternetSales].[TaxAmt],[dbo].[FactInternetSales].[Freight],[dbo].[FactInternetSales].[CarrierTrackingNumber],[dbo].[FactInternetSales].[CustomerPONumber],[dbo].[FactInternetSales].[OrderDate],[dbo].[FactInternetSales].[DueDate],[dbo].[FactInternetSales].[ShipDate] FROM [dbo].[FactInternetSales] 

	annotation _TM_ExtProp_DbTableName = FactInternetSales

	annotation _TM_ExtProp_DbSchemaName = dbo

	annotation TableWidgetSerialization =
			<?xml version="1.0" encoding="UTF-16"?><Gemini xmlns="TableWidgetSerialization"><AnnotationContent><![CDATA[<?xml version="1.0"?>
			<TableWidgetGridSerialization xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			  <ColumnSuggestedType />
			  <ColumnFormat />
			  <ColumnAccuracy />
			  <ColumnCurrencySymbol />
			  <ColumnPositivePattern />
			  <ColumnNegativePattern />
			  <ColumnWidths>
			    <item>
			      <key>
			        <string>ProductKey</string>
			      </key>
			      <value>
			        <int>85</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>OrderDateKey</string>
			      </key>
			      <value>
			        <int>99</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>DueDateKey</string>
			      </key>
			      <value>
			        <int>90</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ShipDateKey</string>
			      </key>
			      <value>
			        <int>91</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>CustomerKey</string>
			      </key>
			      <value>
			        <int>94</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>PromotionKey</string>
			      </key>
			      <value>
			        <int>96</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>CurrencyKey</string>
			      </key>
			      <value>
			        <int>92</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>SalesTerritoryKey</string>
			      </key>
			      <value>
			        <int>115</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>SalesOrderNumber</string>
			      </key>
			      <value>
			        <int>120</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>SalesOrderLineNumber</string>
			      </key>
			      <value>
			        <int>139</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>RevisionNumber</string>
			      </key>
			      <value>
			        <int>107</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>OrderQuantity</string>
			      </key>
			      <value>
			        <int>100</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>UnitPrice</string>
			      </key>
			      <value>
			        <int>72</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ExtendedAmount</string>
			      </key>
			      <value>
			        <int>113</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>UnitPriceDiscountPct</string>
			      </key>
			      <value>
			        <int>128</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>DiscountAmount</string>
			      </key>
			      <value>
			        <int>108</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ProductStandardCost</string>
			      </key>
			      <value>
			        <int>133</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>TotalProductCost</string>
			      </key>
			      <value>
			        <int>113</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>SalesAmount</string>
			      </key>
			      <value>
			        <int>92</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>TaxAmt</string>
			      </key>
			      <value>
			        <int>67</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>Freight</string>
			      </key>
			      <value>
			        <int>64</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>CarrierTrackingNumber</string>
			      </key>
			      <value>
			        <int>140</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>CustomerPONumber</string>
			      </key>
			      <value>
			        <int>127</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>OrderDate</string>
			      </key>
			      <value>
			        <int>81</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>DueDate</string>
			      </key>
			      <value>
			        <int>72</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ShipDate</string>
			      </key>
			      <value>
			        <int>73</int>
			      </value>
			    </item>
			  </ColumnWidths>
			  <ColumnDisplayIndex>
			    <item>
			      <key>
			        <string>ProductKey</string>
			      </key>
			      <value>
			        <int>0</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>OrderDateKey</string>
			      </key>
			      <value>
			        <int>1</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>DueDateKey</string>
			      </key>
			      <value>
			        <int>2</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ShipDateKey</string>
			      </key>
			      <value>
			        <int>3</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>CustomerKey</string>
			      </key>
			      <value>
			        <int>4</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>PromotionKey</string>
			      </key>
			      <value>
			        <int>5</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>CurrencyKey</string>
			      </key>
			      <value>
			        <int>6</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>SalesTerritoryKey</string>
			      </key>
			      <value>
			        <int>7</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>SalesOrderNumber</string>
			      </key>
			      <value>
			        <int>8</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>SalesOrderLineNumber</string>
			      </key>
			      <value>
			        <int>9</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>RevisionNumber</string>
			      </key>
			      <value>
			        <int>10</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>OrderQuantity</string>
			      </key>
			      <value>
			        <int>11</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>UnitPrice</string>
			      </key>
			      <value>
			        <int>12</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ExtendedAmount</string>
			      </key>
			      <value>
			        <int>13</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>UnitPriceDiscountPct</string>
			      </key>
			      <value>
			        <int>14</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>DiscountAmount</string>
			      </key>
			      <value>
			        <int>15</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ProductStandardCost</string>
			      </key>
			      <value>
			        <int>16</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>TotalProductCost</string>
			      </key>
			      <value>
			        <int>17</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>SalesAmount</string>
			      </key>
			      <value>
			        <int>18</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>TaxAmt</string>
			      </key>
			      <value>
			        <int>19</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>Freight</string>
			      </key>
			      <value>
			        <int>20</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>CarrierTrackingNumber</string>
			      </key>
			      <value>
			        <int>21</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>CustomerPONumber</string>
			      </key>
			      <value>
			        <int>22</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>OrderDate</string>
			      </key>
			      <value>
			        <int>23</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>DueDate</string>
			      </key>
			      <value>
			        <int>24</int>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ShipDate</string>
			      </key>
			      <value>
			        <int>25</int>
			      </value>
			    </item>
			  </ColumnDisplayIndex>
			  <ColumnFrozen />
			  <ColumnChecked>
			    <item>
			      <key>
			        <string>OrderDateKey</string>
			      </key>
			      <value>
			        <boolean>false</boolean>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>DueDateKey</string>
			      </key>
			      <value>
			        <boolean>false</boolean>
			      </value>
			    </item>
			    <item>
			      <key>
			        <string>ShipDateKey</string>
			      </key>
			      <value>
			        <boolean>false</boolean>
			      </value>
			    </item>
			  </ColumnChecked>
			  <ColumnFilter />
			  <SelectionFilter />
			  <FilterParameters />
			  <IsSortDescending>false</IsSortDescending>
			</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>

